env {
  parallelism = 1
  job.mode = "BATCH"
  checkpoint.interval = 10000
}

source {
  Jdbc {
    url = "jdbc:postgresql://postgres:5432/source_db"
    driver = "org.postgresql.Driver"
    user = "dw_admin"
    password = "dw_secure_pwd_2025"
    query = "SELECT customer_id, customer_name, email, phone, city, register_date, customer_type FROM business.customers"
  }
}

transform {
  Sql {
    source_table_name = "Jdbc_source_table"
    result_table_name = "enriched"
    query = """
      SELECT *, 'source_db' AS source_system, NOW() AS _ingested_at
      FROM Jdbc_source_table
    """
  }
}

sink {
  Jdbc {
    url = "jdbc:postgresql://postgres:5432/data_warehouse"
    driver = "org.postgresql.Driver"
    user = "dw_admin"
    password = "dw_secure_pwd_2025"
    database = "data_warehouse"
    table = "ods.business_customers"
    schema_save_mode = "CREATE_TABLE_WHEN_NOT_EXIST"
    data_save_mode = "APPEND"
  }
}
