env {
  parallelism = 1
  job.mode = "BATCH"
  checkpoint.interval = 10000
}

source {
  Http {
    url = "https://dummyjson.com/products?limit=100&skip=0"
    method = "GET"
    format = "json"
    json_field = {
      id = "$.products[*].id"
      title = "$.products[*].title"
      description = "$.products[*].description"
      price = "$.products[*].price"
      discount_percentage = "$.products[*].discountPercentage"
      rating = "$.products[*].rating"
      stock = "$.products[*].stock"
      brand = "$.products[*].brand"
      category = "$.products[*].category"
      thumbnail = "$.products[*].thumbnail"
    }
    schema = {
      fields {
        id = int
        title = string
        description = string
        price = double
        discount_percentage = double
        rating = double
        stock = int
        brand = string
        category = string
        thumbnail = string
      }
    }
  }
}

transform {
  Sql {
    source_table_name = "Http_source_table"
    result_table_name = "enriched"
    query = """
      SELECT *, 'dummyjson' AS source_system, NOW() AS _ingested_at
      FROM Http_source_table
    """
  }
}

sink {
  Jdbc {
    url = "jdbc:postgresql://postgres:5432/data_warehouse"
    driver = "org.postgresql.Driver"
    user = "dw_admin"
    password = "dw_secure_pwd_2025"
    database = "data_warehouse"
    table = "ods.ecommerce_products"
    schema_save_mode = "CREATE_TABLE_WHEN_NOT_EXIST"
    data_save_mode = "APPEND"
  }
}
