seatunnel:
  engine:
    backup-count: 1
    print-execution-info-interval: 10
    slot-service:
      dynamic-slot: true
    checkpoint:
      interval: 10000
      timeout: 60000
      storage:
        type: localfile
        max-retained: 3
        plugin-config:
          namespace: /tmp/seatunnel/checkpoint/
